# Configuración mínima BIRD 3
router id 127.0.0.1;

# Tables to store ROAs
roa4 table ipv4_prefix_table;
roa6 table ipv6_prefix_table;
# Table to store ASPA
aspa table aspa_table;

# RPKI protocol to connect RTR server
protocol rpki my_rpki {
    # Address and port of RTR server
    remote "127.0.0.1" port 8323;
    
    # Define where data it will be stored
    roa4 { table ipv4_prefix_table; };
    roa6 { table ipv6_prefix_table; };
    aspa { table aspa_table; };
    
    # Refresh times
    retry 10;
    expire 600;
}