! Router identity configuration
hostname rapport
log syslog informational
service integrated-vtysh-config
!
router bgp 65001
exit
!
rpki
 rpki cache tcp 127.0.0.1 8323 preference 1
exit
!
! VTYSH CONFIGURATION
! Allow vtysh to handle everything in this single file
line vty
!